### ISSUE TITLE
Proxy a list of URLs through the tunnel - CLI 

### ISSUE THREAD

**Issue by eliranw** [we-dcode/kubetunnel#17]
2. Add --proxy flags to kubetunnel-cli that sends their values through the CR spec.
   2.1. Add the flag itself - can be used multiple times [X]
   2.2. Parse the flag/s and send the values to the cr spec. [X]
   2.3 Add the DNS to the hosts file - send them to kubetunnel-server service. [X]

**Comment by maordavidov** [comment]
Done, @tamirshaul please make sure you're adding the proxy port to kubetunnel service, otherwise the client will not be able to port-forward to the proxy.
